name: dbt_airflow_project

profile: dbt_airflow_project

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  # Builds seeds into '<your_schema_name>_raw'
  dbt_airflow_project:
    +schema: raw

models:
  dbt_airflow_project:
    # Materialize staging models as views, and marts as tables
    staging:
      +materialized: view
    marts:
      +materialized: table
